# PyTorch PR PyTorch Tests Builds Pipeline on Azure DevOps
#
# This pipeline runs custom PyTorch unit-tests on PyTorch 
# wheels generated during PR builds.

stages:
- stage: 'EnsureArtifactsReady'
  displayName: 'Ensure PyTorch PR Linux GPU Artifacts are ready'
  jobs:
  - template: job_templates/check-artifact-status-template.yml
    parameters:
      name: Verify
      pool: $(BUILD_POOL_VMSS_BURSTABLE)
      customMatrixes:
        Ubuntu:
          TARGET_CIRCLECI_BUILD: $(TARGET_CIRCLECI_PR_TEMP_CUDA_111)

- stage: 'PRCustomTests'
  displayName: 'Run custom unit tests on PyTorch wheels'
  jobs:
  - template: job_templates/pytorch-template-unix.yml
    parameters:
      name: ubuntu_1804_GPU_docker
      pool: $(BUILD_POOL_PR)
      container_endpoint: pytorchms.azurecr.io
      customMatrixes:
        PR_Custom_Tests:
          container_image: $(CONTAINER_IMAGE_PR_TEMP_CUDA_111)
          PYTHON_VERSION: $(PYTHON_VERSION_PR)
          CUDA_VERSION: $(CUDA_VERSION_PR_TEMP_CUDA_111)
          TARGET_CIRCLECI_BUILD: $(TARGET_CIRCLECI_PR_TEMP_CUDA_111)
          RUN_TESTS: $(RUN_TESTS_PR)
 