parameters:
  name: ''
  pool: ''

jobs:
- job: ${{parameters.name}}
  timeoutInMinutes: 600
  pool:
    name: ${{ parameters.pool}}
  steps:
  # Clone PyTorch Tests repository
  - bash: |
      B64_PAT=$(printf "%s"":$_ADOTOKEN" | base64)
      git -c http.extraHeader="Authorization: Basic ${B64_PAT}" clone $(AZURE_DEVOPS_PYTORCH_TESTS_REPO_URL)
      cd pytorch_tests
      git checkout $(PYTORCH_TESTS_CHECKOUT_BRANCH)
    env:
      _ADOTOKEN: $(AZURE_DEVOPS_CLI_PAT)
    displayName: Clone PyTorch Tests repo
  - bash: |
      pip install -r $(Build.SourcesDirectory)/pytorch_tests/scripts/webapp/requirements.txt
      python $(Build.SourcesDirectory)/pytorch_tests/scripts/webapp/notify-webapp.py
    displayName: Notify Webapp