parameters:
  name: ''
  pool: ''

jobs:
- job: ${{parameters.name}}
  timeoutInMinutes: 600
  pool:
    name: ${{ parameters.pool}}
  # container:
  #   image: ${{ parameters.container_image }}
  #   endpoint: ${{ parameters.container_endpoint }}
  steps:
  # Clone PyTorch Tests repository
  - bash: |
      B64_PAT=$(printf "%s"":$_ADOTOKEN" | base64)
      git -c http.extraHeader="Authorization: Basic ${B64_PAT}" clone $(AZURE_DEVOPS_PYTORCH_TESTS_REPO_URL)
      cd pytorch_tests
      git checkout $(PYTORCH_TESTS_CHECKOUT_BRANCH)
    env:
      _ADOTOKEN: $(AZURE_DEVOPS_CLI_PAT)
    displayName: Clone PyTorch Tests repo
  - bash: |
      bash $(Build.SourcesDirectory)/pytorch_tests/webapp/notify_webapp.sh
    displayName: Notify Webapp