# PyTorch build steps template with Unix images Azure DevOps Instances
#
# This build depends on 5 parameters set as an environment variables in the pipeline:
#   - AZURE_DEVOPS_CLI_PAT: Secret var for authenticating to Azure DevOps
#   - AZURE_STORAGE_KEY: Secret var for authenticating to Azure Storage
#   - TS_CLONE_P, TS_P, TS_SM_P: Secret vars for specific unit tests

parameters:
  name: ''
  pool: ''
  container_endpoint: ''
  customMatrixes: ''

jobs:
- job: ${{parameters.name}}
  timeoutInMinutes: 600
  strategy:
    matrix:
      ${{ insert }}: ${{parameters.customMatrixes}}
  pool:
    name: ${{ parameters.pool}}
  variables:
    DECODE_PERCENTS: false
  container:
    image: $[variables['container_image']]
    endpoint: ${{parameters.container_endpoint}}

  steps:
  # Delete pytorch_tests repo from previous builds if exists
  - bash: rm -rf pytorch_tests/
    displayName: Delete pytorch_tests repo from previous builds if exists

  # Clone PyTorch Tests repository
  - bash: |
      B64_PAT=$(printf "%s"":$ADOTOKEN" | base64)
      git -c http.extraHeader="Authorization: Basic ${B64_PAT}" clone $(AZURE_DEVOPS_PYTORCH_TESTS_REPO_URL)
      cd pytorch_tests
    env:
      ADOTOKEN: $(AZURE_DEVOPS_CLI_PAT)
    displayName: Clone PyTorch Tests repo

  # Run PyTorch Unit Tests
  - bash: bash $(Build.SourcesDirectory)/pytorch_tests/scripts/linux/run.sh
    env:
      ADOTOKEN: $(AZURE_DEVOPS_CLI_PAT)
      AZURE_S_K: $(AZURE_STORAGE_KEY)
      TS_CLONE_P: $(TS_CLONE_PASSWORD)
      TS_P: $(TS_PAT)
      TS_SM_P: $(TS_SM_PAT)
    displayName: Run PyTorch Unit Tests
